@startuml

actor AD as "ADMIN"

rectangle Database

rectangle "WORLD APPLICATION" {
    usecase UCa as "Get Report Type"

    usecase UCb as "Select Specific Report"

    usecase UCc as "Input Params for report"

    usecase UCd as "print to screen"

    AD - UCa
    UCa ..> UCb
     UCb ..> UCc : extends
     Database ..> UCd : return results
     UCd ..> UCa
     UCb ..> Database :request

    UCc - Database : request
}

@enduml